 import Container from "@/components/Container";
import { useRouter } from 'next/router';
import { usePostById } from '@/hooks/usePostById';
import Head from 'next/head';
import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
    BreadcrumbPage,
    BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"

import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import Image from "next/image";
import { urlForImage } from "@/sanity/lib/image";
import Footer from "@/components/Footer";
import { CardBody, CardContainer, CardItem } from "@/components/ui/3d-card";


export default function BlogPage() {
    const router = useRouter();
    const { id } = router.query;

    // Fetch post data based on id
    const post = usePostById(id);

    return (
        <>
            <Head>
                <title>Fleet-blog/blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="favicon.ico" />
            </Head>

            <Providers>
                <Navbar />
                <Container>
                <div className='flex flex-col justify-center items-center'>

                        {/* Conditional rendering based on whether post data is available */}
                         {post ? ( 
                            <div className=" py-4  items-center">

                                <Breadcrumb className="mt-4">
                                    <BreadcrumbList>
                                        <BreadcrumbItem>
                                            <BreadcrumbLink href="/">Home</BreadcrumbLink>
                                        </BreadcrumbItem>
                                        <BreadcrumbSeparator />
                                        <BreadcrumbItem>
                                            <BreadcrumbLink href="/blog">Blogs</BreadcrumbLink>
                                        </BreadcrumbItem>
                                        <BreadcrumbSeparator />
                                        <BreadcrumbItem>
                                            <BreadcrumbPage>{post.slug}</BreadcrumbPage>
                                        </BreadcrumbItem>
                                    </BreadcrumbList>
                                </Breadcrumb>

                                <div>
                                    <p className="flex justify-center text-2xl font-bold pt-8">{post.title}</p>
                                    {post.mainImage && (
                                    <CardContainer className="inter-var">
                                    <CardBody className="relative group/card  dark:hover:shadow-2xl dark:hover:shadow-emerald-500/[0.1] w-auto sm:w-[30rem] h-auto rounded-xl p-0 ">
                                     
                                       <CardItem translateZ="100" className="w-full mt-0">
                                           <Image
                                               src={urlForImage(post?.mainImage.asset)}
                                               alt={post.title}
                                               width={500}
                                               height={500}
                                               className="h-60 w-full object-cover rounded-xl group-hover/card:shadow-xl"
                                               priority={false}
                                               quality={80}
                                               placeholder={"empty"}
                                             />
                                         </CardItem>
                           
                                   </CardBody>
                                 </CardContainer>
                                    )}
                                    <p className="flex justify-center">Created: {post._createdAt}</p>
                                    <br />
                                    <p className="pt-6">{post.body}</p>
                                </div>
                            </div>
                         ) : (
                            <p>Loading...</p>
                        )} 
                    </div>
                </Container>
                <Footer />
            </Providers>
        </>
    );
}
 