 import Container from "@/components/Container";
import { useRouter } from 'next/router';
import { usePostById } from '@/hooks/usePostById';
import Head from 'next/head';
import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
    BreadcrumbPage,
    BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"

import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import Image from "next/image";
import { urlForImage } from "@/sanity/lib/image";


export default function BlogPage() {
    const router = useRouter();
    const { id } = router.query;

    // Fetch post data based on id
    const post = usePostById(id);

    return (
        <>
            <Head>
                <title>Fleet-blog/blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="favicon.ico" />
            </Head>

            <Providers>
                <Navbar />
                <Container>
                <div className='flex flex-col justify-center items-center'>

                        {/* Conditional rendering based on whether post data is available */}
                         {post ? ( 
                            <div className="md:w-1/2 py-4  items-center">

                                <Breadcrumb className="mt-4">
                                    <BreadcrumbList>
                                        <BreadcrumbItem>
                                            <BreadcrumbLink href="/">Home</BreadcrumbLink>
                                        </BreadcrumbItem>
                                        <BreadcrumbSeparator />
                                        <BreadcrumbItem>
                                            <BreadcrumbLink href="/blog">Blogs</BreadcrumbLink>
                                        </BreadcrumbItem>
                                        <BreadcrumbSeparator />
                                        <BreadcrumbItem>
                                            <BreadcrumbPage>{post.slug}</BreadcrumbPage>
                                        </BreadcrumbItem>
                                    </BreadcrumbList>
                                </Breadcrumb>

                                <div>
                                    <p className="flex justify-center text-2xl font-bold pt-8">{post.title}</p>
                                    {post.mainImage && (
                                    <Image
                                         src={urlForImage(post?.mainImage.asset)}
                                         alt={post.title}
                                         width={500}
                                         height={500}
                                         className="h-60 w-full my-6 object-cover rounded-xl group-hover/card:shadow-xl"
                                         priority={false}
                                         quality={80}
                                         placeholder={"empty"}
                                    />
                                    )}
                                    <p className="flex justify-center pt-2">Created: {post._createdAt}</p>
                                    <br />
                                    <p className="pt-8">{post.body}</p>
                                </div>
                            </div>
                         ) : (
                            <p>Loading...</p>
                        )} 
                    </div>
                </Container>
            </Providers>
        </>
    );
}
 