import { useFeatureById } from '@/hooks/useFeatureById'; 
import { useRouter } from 'next/router';
import Image from "next/image";
import { urlForImage } from "@/sanity/lib/image";
import Navbar from "@/components/Navbar";
import Head from 'next/head';
import Providers from "@/components/Providers";
import Container from "@/components/Container";


function FeatureIndex() {
  
  const router = useRouter();
    const { id } = router.query;
  
  const feature = useFeatureById(id);

  // Render the fetched feature data
  return (
    <div>

      <Head>
          <title>Fleet-Feature</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.ico" />
      </Head>
      <Providers>
      <Navbar />

      <Container>
    
      <div className='flex flex-col justify-center items-center'>
      
        {feature ? (
          <div className="md:w-1/2 py-4  items-center">
          <h1 className="text-2xl font-bold flex justify-center items-center h-full mb-8">{feature?.title}</h1>

          {feature.image && (
            <Image
              src={urlForImage(feature.image.asset)}
              alt="Picture"
              width={200}
              height={200}
              quality={80}
              priority={false}
              placeholder="empty"
              className="h-60 w-full object-cover rounded-xl group-hover/card:shadow-xl my-6"
            />
          )}

        <h1 className="font-medium text-xl mb-6">Subtitle: {feature?.subtitle} </h1>
        
        <p className="">{feature?.summary}</p>
        

        
        </div>
      ) : (
        <p>Loading...</p>
      )}
    </div>
    </Container>
    </Providers>
    </div>
  );
}

export default FeatureIndex;









