import Container from "@/components/Container";
import Navbar from "@/components/Navbar";
import { usePosts } from "@/hooks/usePosts";
import { urlForImage } from "@/sanity/lib/image";
import Image from "next/image";
import React from "react";
import Head from 'next/head';
import Link from 'next/link';
import Providers from "@/components/Providers";
import { CardBody, CardContainer, CardItem } from "@/components/ui/3d-card";
//import BlockContent from '@sanity/block-content-to-react';

const Blog = () => {
  const posts = usePosts();
  return (
    <div>

      <Head>
          <title>Fleet-Blog/Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.ico" />
      </Head>
      <Providers>
      <Navbar />
      <Container>
        <div className="container mx-auto p-4">
          <h1 className="text-4xl font-bold mb-4">Latest Blogs</h1>
        </div>
        {posts.map((post, index) => (
          <div
            key={index}
            className="mx-auto p-4 border-b border-gray-300
              grid sm:grid-cols-1 md:grid-cols-2 gap-8
              "
          >
            {/* console.log(post?._id); */}
            
            <h2 className="text-2xl font-bold mb-2">
            <Link
              href={{
                pathname: `/blog/${index}`,
                query: {
                  id: post?._id,
                  title: post?.title,
                  //body: JSON.stringify(post),
                  body: post?.body,
                  createdAT: post?._createdAt,
                
                },
              }}
              className="text-black hover:text-gray-600 text-3xl"
              >
                <strong>{post?.title}</strong>
              </Link>
              </h2>

              <CardContainer className="inter-var">
                 <CardBody className="bg-[#f4f1ea] relative group/card  dark:hover:shadow-2xl dark:hover:shadow-emerald-500/[0.1] dark:bg-black w-auto sm:w-[30rem] h-auto rounded-xl p-6 border  ">
                  
                    <CardItem translateZ="100" className="w-full mt-4">
                        <Image
                            src={urlForImage(post?.mainImage.asset)}
                            alt={post.title}
                            width={500}
                            height={500}
                            className="h-60 w-full object-cover rounded-xl group-hover/card:shadow-xl"
                            priority={false}
                            quality={80}
                            placeholder={"empty"}
                          />
                      </CardItem>
        
                </CardBody>
              </CardContainer>

          {/*   <Image
              src={urlForImage(post?.mainImage.asset)}
              alt="Picture"
              width={200}
              height={200}
              quality={80}
              priority={false}
              placeholder={"empty"}
              className="w-full h-full md:w-auto md:h-auto object-cover"
            /> */}


            <p>{post?.body}</p>
          </div>
        ))}
      </Container>
      </Providers>
    </div>
  );
};

export default Blog;
