"use client"

import React from 'react'

import { useRouter } from 'next/router';
import Image from 'next/image';
import { urlForImage } from "@/sanity/lib/image";
import Link from 'next/link';
import Navbar from '@/components/Navbar';
import Providers from '@/components/Providers';
import { useHeroSectionById } from '@/hooks/useHeroSectionById';
import Head from 'next/head';
import Container from '@/components/Container';
import { CardBody, CardContainer, CardItem } from "@/components/ui/3d-card";
import Footer from '@/components/Footer';


const MyHero = () => {
    const router = useRouter();
    const { id } = router.query;

    const hero = useHeroSectionById(id);
  
    return (
      <div>
  
        <Head>
            <title>Fleet-Feature</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="favicon.ico" />
        </Head>
        <Providers>
        <Navbar />
      <Container>
      <div className='flex flex-col justify-center items-center'>
        
        {hero ? (
          <div className="py-4  items-center">
          <h1 className="text-2xl font-bold flex justify-center items-center h-full mb-8">{hero?.title}</h1>
  
          {hero.image && (
              <CardContainer className="inter-var">
              <CardBody className="relative group/card  dark:hover:shadow-2xl dark:hover:shadow-emerald-500/[0.1] w-auto sm:w-[30rem] h-auto rounded-xl p-0 ">
               
                 <CardItem translateZ="100" className="w-full mt-0">
                     <Image
                         src={urlForImage(hero?.image.asset)}
                         alt={hero.title}
                         width={500}
                         height={500}
                         className="h-60 w-full object-cover rounded-xl group-hover/card:shadow-xl"
                         priority={false}
                         quality={80}
                         placeholder={"empty"}
                       />
                   </CardItem>
     
             </CardBody>
           </CardContainer>
            )}
  
          <h1 className="font-medium text-xl mb-6">Subtitle: {hero?.subtitle} </h1>
          
          <p className="">{hero?.summary}</p>
          
  
          
          </div>
        ) : (
          <p>Loading...</p>
        )}
      </div>
      </Container>
      <Footer />
      </Providers>
      </div>
    );
  }
  
  export default MyHero;